version: "3.8"

services:
  crud-api:
    build: .
    container_name: products-crud
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
