version: '3.8'

volumes:
  datamongo: 
  data-elasticsearch:
  data-mongo:

services:
  nginx:
    image: nginx:1.21.1-alpine
    container_name: gio_am_nginx
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - management
      - gateway
      - webui

  mongodb-am:
    image: mongo:4.2
    container_name: gio_am_mongodb
    restart: always
    volumes:
      - datamongo:/data/db
      - ./logs/am-mongodb:/var/log/mongodb

  mongodb-apim:
    image: mongo:${MONGODB_VERSION:-6.0.8}
    container_name: gio_apim_mongodb
    restart: always
    volumes:
      - data-mongo:/data/db
    networks:
      - storage
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-8.8.1}
    container_name: gio_apim_elasticsearch
    restart: always
    volumes:
      - data-elasticsearch:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536
    networks:
      - storage

  ############
  # AM
  ############
  gateway:
    image: graviteeio/am-gateway:${GIO_AM_VERSION}
    container_name: gio_am_gateway
    restart: always
    links:
      - mongodb-am
    depends_on:
      - mongodb-am
    volumes:
      - ./logs/am-gateway:/etc/gravitee.io/log
      - ./license/license.key:/opt/graviteeio-am-gateway/license/license.key
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb-am:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_oauth2_mongodb_uri=mongodb://mongodb-am:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000

  management:
    image: graviteeio/am-management-api:${GIO_AM_VERSION}
    container_name: gio_am_management
    restart: always
    links:
      - mongodb-am
    depends_on:
      - mongodb-am
    volumes:
      - ./logs/am-management-api:/etc/gravitee.io/log
      - ./license/license.key:/opt/graviteeio-am-management-api/license/license.key
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb-am:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_oauth2_mongodb_uri=mongodb://mongodb-am:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000

  webui:
    image: graviteeio/am-management-ui:${GIO_AM_VERSION}
    container_name: gio_am_webui
    restart: always
    depends_on:
      - management
    environment:
      - MGMT_API_URL=http://localhost:${NGINX_PORT}/am
      - MGMT_UI_URL=http://localhost:${NGINX_PORT}/am/ui
    volumes:
      - ./logs/am-webui:/var/log/httpd


  ############
  # APIM
  ############



  gateway-apim:
    image: graviteeio/apim-gateway:${APIM_VERSION:-4}
    container_name: gio_apim_gateway
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - mongodb-apim
      - elasticsearch
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb-apim:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_ratelimit_mongodb_uri=mongodb://mongodb-apim:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_reporters_elasticsearch_endpoints_0=http://elasticsearch:9200
    volumes:
      - ./logs/apim-gateway:/etc/gravitee.io/log
      - ./license/license.key:/opt/graviteeio-gateway/license/license.key
    networks:
      - storage
      - frontend

  management_api:
    image: graviteeio/apim-management-api:${APIM_VERSION:-4}
    container_name: gio_apim_management_api
    restart: always
    ports:
      - "8083:8083"
    links:
      - mongodb-apim
      - elasticsearch
    depends_on:
      - mongodb-apim
      - elasticsearch
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb-apim:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_analytics_elasticsearch_endpoints_0=http://elasticsearch:9200
      - gravitee_installation_standalone_portal_url=http://localhost:8085
    volumes:
      - ./logs/apim-management-api:/etc/gravitee.io/log
      - ./license/license.key:/opt/graviteeio-gateway/license/license.key
    networks:
      - storage
      - frontend

  management_ui:
    image: graviteeio/apim-management-ui:${APIM_VERSION:-4}
    container_name: gio_apim_management_ui
    restart: always
    ports:
      - "8084:8080"
    depends_on:
      - management_api
    environment:
      - MGMT_API_URL=http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/
    networks:
      - frontend

  portal_ui:
    image: graviteeio/apim-portal-ui:${APIM_VERSION:-4}
    container_name: gio_apim_portal_ui
    restart: always
    ports:
      - "8085:8080"
    depends_on:
      - management_api
    environment:
      - PORTAL_API_URL=http://localhost:8083/portal/environments/DEFAULT
    networks:
      - frontend

networks:
  frontend:
      name: frontend
  storage:
      name: storage